version: '3.8'

services:
  nginx-proxy:
    build:
      context: ./nginx-proxy
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - planejador-frontend
      - planejador-backend
    networks:
      - app-network
    restart: unless-stopped

  planejador-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: planejador_backend
    expose:
      - "3001"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - app-network
    restart: unless-stopped

  planejador-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: planejador_frontend
    expose:
      - "80"
    depends_on:
      - planejador-backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  data_volume:
    driver: local